### ISSUE TITLE
epg_infos: handle traffic stats that are set to ""

### ISSUE THREAD

**Issue by camrossi** [datacenter/aci-monitoring-stack#25]
If not traffic has been received the traffic stat might be set to "" 

We should add to all the queries this:

```
        value_transform:
          '': 0
```

For Example
```
      - name: epg_rx_multicast
        value_name: vlanCktEp.children.[l2IngrBytes5min].attributes.multicastCum
        value_transform:
          '': 0
```
